# version: "3.9"
services:
  mysql:
    image: mysql:9.1
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./beautybook-backend
    container_name: beautybook-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:5000/api/health || exit 1
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
      - ./beautybook-backend:/app
      - ./beautybook-backend/prisma:/app/prisma
    command: >
      sh -c "npx prisma migrate deploy --schema=/app/prisma/schema.prisma && npx prisma generate && pm2 start app.js -i max --no-daemon"

  frontend:
    build:
      context: ./beautybook-frontend
    container_name: beautybook-frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    # volumes:
      # - ./beautybook-frontend:/app
    stdin_open: true
    tty: true
    # command: >
    #   sh -c "npm run build && serve -s -n build -l 3000 --single"

volumes:
  mysql-data:
